/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlbds.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dialog;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.time.Duration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import qlbds.helper.DialogHelper;
import qlbds.helper.ShareHelper;

/**
 *
 * @author ntqba
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("TRANG CHỦ QUẢN LÝ BẤT ĐỘNG SẢN");
        setIconImage(ShareHelper.getAppIcon());
        pnlMain.add(pnlHeader, BorderLayout.PAGE_START);
        pnlMain.add(pnlItems, BorderLayout.CENTER);
        pnlMain.add(pnlMenu, BorderLayout.WEST);
        pack();
        setLocationRelativeTo(null);
    }
    /*
    width: 213
    height: 549
     */

    int width = 213;
    int height = 549;

    //Phương thức mở menu
    private void OpenMenuBar() {
        //tạo luồng chạy song song với luồng chính (Main)
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    pnlMenu.setPreferredSize(new Dimension(i, height));
                    pnlMain.revalidate();
                    pnlMain.repaint();
                    //Mở từ từ
                    try {
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    //Phương thức đóng menu
    private void CloseMenuBar() {
        //tạo luồng chạy song song với luồng chính (Main)
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i--) {
                    pnlMenu.setPreferredSize(new Dimension(i, height));
                    pnlMain.revalidate();
                    pnlMain.repaint();
                    try {
                        //Đóng từ từ
                        Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
 void openWebsite() {
        try {
            Desktop.getDesktop().browse(new File("C:\\Users\\baont\\Desktop\\web\\huongdan.html").toURI());
        } catch (IOException ex) {
            DialogHelper.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblBatDongSan = new javax.swing.JLabel();
        lblDonHang = new javax.swing.JLabel();
        lblDatMua = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        lblNguoiMua = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        lblGioiThieu = new javax.swing.JLabel();
        lblDoiMK = new javax.swing.JLabel();
        lblDN = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlItems = new javax.swing.JPanel();
        btnQLNV = new javax.swing.JButton();
        btnQlBDS = new javax.swing.JButton();
        btnQlDonHang = new javax.swing.JButton();
        btnQlDatMua = new javax.swing.JButton();
        btnQlKhachHang = new javax.swing.JButton();
        btnQlNguoiMua = new javax.swing.JButton();
        btnThongkeDoanhThu = new javax.swing.JButton();
        btnThongKeGia = new javax.swing.JButton();
        btnGioiThieu = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();

        pnlMenu.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTrangChu.setText("Trang Chủ ");
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseEntered(evt);
            }
        });

        lblNhanVien.setText("Quản Lý Nhân Viên");
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseClicked(evt);
            }
        });

        lblBatDongSan.setText("Quản Lý Bất Động Sản");
        lblBatDongSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBatDongSanMouseClicked(evt);
            }
        });

        lblDonHang.setText("Quản Lý Đơn Hàng");
        lblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDonHangMouseClicked(evt);
            }
        });

        lblDatMua.setText("Quản Lý Đặt Mua");
        lblDatMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatMuaMouseClicked(evt);
            }
        });

        lblKhachHang.setText("Quản Lý Khách Hàng");
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
        });

        lblNguoiMua.setText("Quản Lý Người Mua");
        lblNguoiMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNguoiMuaMouseClicked(evt);
            }
        });

        lblDoanhThu.setText("Thống Kê Doanh Thu");
        lblDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseClicked(evt);
            }
        });

        lblGia.setText("Thống Kê BĐS Theo Giá");
        lblGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiaMouseClicked(evt);
            }
        });

        jLabel10.setText("Trợ Giúp");

        lblGioiThieu.setText("Giới Thiệu");
        lblGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseClicked(evt);
            }
        });

        lblDoiMK.setText("Đổi Mật Khẩu");
        lblDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMKMouseClicked(evt);
            }
        });

        lblDN.setText("Đăng Xuất");
        lblDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDNMouseClicked(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Home.png"))); // NOI18N

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close1.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrangChu)
                    .addComponent(lblNhanVien)
                    .addComponent(lblBatDongSan)
                    .addComponent(lblDonHang)
                    .addComponent(lblDatMua)
                    .addComponent(lblKhachHang)
                    .addComponent(lblNguoiMua)
                    .addComponent(lblDoanhThu)
                    .addComponent(lblGia)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblGioiThieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDoiMK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClose)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangChu)
                .addGap(18, 18, 18)
                .addComponent(lblNhanVien)
                .addGap(18, 18, 18)
                .addComponent(lblBatDongSan)
                .addGap(18, 18, 18)
                .addComponent(lblDonHang)
                .addGap(18, 18, 18)
                .addComponent(lblDatMua)
                .addGap(18, 18, 18)
                .addComponent(lblKhachHang)
                .addGap(18, 18, 18)
                .addComponent(lblNguoiMua)
                .addGap(18, 18, 18)
                .addComponent(lblDoanhThu)
                .addGap(18, 18, 18)
                .addComponent(lblGia)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lblGioiThieu)
                .addGap(18, 18, 18)
                .addComponent(lblDoiMK)
                .addGap(18, 18, 18)
                .addComponent(lblDN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHeader.setBackground(new java.awt.Color(51, 153, 255));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("HỆ THỐNG QUẢN LÝ BẤT ĐỘNG SẢN");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("\"Đầu tư hiện tại - Phát triển tương lai\"");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(lblMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlItems.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        btnQLNV.setBackground(new java.awt.Color(0, 102, 255));
        btnQLNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/icon/role.png"))); // NOI18N
        btnQLNV.setText("Quản Lý Nhân Viên");
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        pnlItems.add(btnQLNV);

        btnQlBDS.setBackground(new java.awt.Color(0, 153, 51));
        btnQlBDS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQlBDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Home.png"))); // NOI18N
        btnQlBDS.setText("Quản Lý Bất Động Sản");
        btnQlBDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlBDSActionPerformed(evt);
            }
        });
        pnlItems.add(btnQlBDS);

        btnQlDonHang.setBackground(new java.awt.Color(255, 102, 255));
        btnQlDonHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQlDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/List.png"))); // NOI18N
        btnQlDonHang.setText("Quản Lý Đơn Hàng");
        btnQlDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlDonHangActionPerformed(evt);
            }
        });
        pnlItems.add(btnQlDonHang);

        btnQlDatMua.setBackground(new java.awt.Color(102, 102, 0));
        btnQlDatMua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQlDatMua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Blue key.png"))); // NOI18N
        btnQlDatMua.setText("Quản Lý Đặt Mua");
        btnQlDatMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlDatMuaActionPerformed(evt);
            }
        });
        pnlItems.add(btnQlDatMua);

        btnQlKhachHang.setBackground(new java.awt.Color(102, 0, 102));
        btnQlKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQlKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Female.png"))); // NOI18N
        btnQlKhachHang.setText("Quản Lý Khách Hàng");
        btnQlKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlKhachHangActionPerformed(evt);
            }
        });
        pnlItems.add(btnQlKhachHang);

        btnQlNguoiMua.setBackground(new java.awt.Color(102, 102, 102));
        btnQlNguoiMua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQlNguoiMua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/User group.png"))); // NOI18N
        btnQlNguoiMua.setText("Quản Lý Người Mua");
        btnQlNguoiMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQlNguoiMuaActionPerformed(evt);
            }
        });
        pnlItems.add(btnQlNguoiMua);

        btnThongkeDoanhThu.setBackground(new java.awt.Color(255, 0, 0));
        btnThongkeDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongkeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Dollar.png"))); // NOI18N
        btnThongkeDoanhThu.setText("Thống Kê Doanh Thu");
        btnThongkeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeDoanhThuActionPerformed(evt);
            }
        });
        pnlItems.add(btnThongkeDoanhThu);

        btnThongKeGia.setBackground(new java.awt.Color(51, 255, 255));
        btnThongKeGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKeGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/3d bar chart.png"))); // NOI18N
        btnThongKeGia.setText("Thống Kê BĐS Theo Giá");
        btnThongKeGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeGiaActionPerformed(evt);
            }
        });
        pnlItems.add(btnThongKeGia);

        btnGioiThieu.setBackground(new java.awt.Color(204, 204, 0));
        btnGioiThieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/vn/icon/Earth.png"))); // NOI18N
        btnGioiThieu.setText("Giới thiệu");
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        pnlItems.add(btnGioiThieu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked

        OpenMenuBar();
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseEntered
        lblTrangChu.setBackground(Color.yellow);
    }//GEN-LAST:event_lblTrangChuMouseEntered

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        CloseMenuBar();        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        if (!ShareHelper.isManager()) {
            DialogHelper.alert(this, "Bạn không được quyền vào trang này!!");
        } else {
            new QuanlynhanvienJFrame().setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnQlBDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlBDSActionPerformed
        
        new Quanlybatdongsan().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQlBDSActionPerformed

    private void btnQlDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlDonHangActionPerformed
        new QuanlydonhangJFrame().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnQlDonHangActionPerformed

    private void btnQlDatMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlDatMuaActionPerformed
        new Quanlydatmua().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnQlDatMuaActionPerformed

    private void btnQlKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlKhachHangActionPerformed
        new QuanlykhachhangJFrame().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnQlKhachHangActionPerformed

    private void btnQlNguoiMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQlNguoiMuaActionPerformed
        new QuanlynguoimuaJFrame().setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnQlNguoiMuaActionPerformed

    private void btnThongkeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeDoanhThuActionPerformed
openThongKe(1);
    }//GEN-LAST:event_btnThongkeDoanhThuActionPerformed

    private void btnThongKeGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeGiaActionPerformed
        openThongKe(0);
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThongKeGiaActionPerformed

    private void lblTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseClicked
openWebsite();         // TODO add your handling code here:
    }//GEN-LAST:event_lblTrangChuMouseClicked

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
 if (!ShareHelper.isManager()) {
            DialogHelper.alert(this, "Bạn không được quyền vào trang này!!");
        } else {
            new QuanlynhanvienJFrame().setVisible(true);
        }
    }//GEN-LAST:event_lblNhanVienMouseClicked

    private void lblBatDongSanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatDongSanMouseClicked
 new Quanlybatdongsan().setVisible(true); 
    }//GEN-LAST:event_lblBatDongSanMouseClicked

    private void lblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonHangMouseClicked
        new QuanlydonhangJFrame().setVisible(true);
    }//GEN-LAST:event_lblDonHangMouseClicked

    private void lblDatMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatMuaMouseClicked
        new Quanlydatmua().setVisible(true); 
    }//GEN-LAST:event_lblDatMuaMouseClicked

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        new QuanlykhachhangJFrame().setVisible(true);
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblNguoiMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiMuaMouseClicked
new QuanlynguoimuaJFrame().setVisible(true);  
    }//GEN-LAST:event_lblNguoiMuaMouseClicked

    private void lblDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseClicked
openThongKe(1);
    }//GEN-LAST:event_lblDoanhThuMouseClicked

    private void lblGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaMouseClicked
openThongKe(0);
    }//GEN-LAST:event_lblGiaMouseClicked

    private void lblDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMKMouseClicked
        new ChangePass1().setVisible(true);
    }//GEN-LAST:event_lblDoiMKMouseClicked

    private void lblDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDNMouseClicked
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDNMouseClicked

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
openWebsite();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void lblGioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseClicked
openWebsite();         // TODO add your handling code here:
    }//GEN-LAST:event_lblGioiThieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQlBDS;
    private javax.swing.JButton btnQlDatMua;
    private javax.swing.JButton btnQlDonHang;
    private javax.swing.JButton btnQlKhachHang;
    private javax.swing.JButton btnQlNguoiMua;
    private javax.swing.JButton btnThongKeGia;
    private javax.swing.JButton btnThongkeDoanhThu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBatDongSan;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDN;
    private javax.swing.JLabel lblDatMua;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblDoiMK;
    private javax.swing.JLabel lblDonHang;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNguoiMua;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlItems;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
void openThongKe(int index) {
if(ShareHelper.isLogin()){
            if(index == 1 &&!ShareHelper.isManager()){
                DialogHelper.alert(this, "Bạn không có quyền xem thông tin doanh thu");
                return;
            }
            Tonghopthongke tkwin = new Tonghopthongke();
            tkwin.selecTab(index);
            tkwin.setVisible(true);
            this.dispose();
        }
        else{
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }
}
